### ISSUE TITLE
Hi billiana. A small observation to my code pls.

### ISSUE THREAD

**Issue by rene-mdd** [rene-mdd/react-redux-blog-rene-mdd#2]
https://github.com/dci-ber-fbw21/spa-store-blog-comments-rene-mdd/blob/bcf53bd46678a02c67a93096ef80961783960bf8/src/store/app-reducer.js#L28

@Bilie hi! can you quickly check this line of code. Is this the correct way of deleting items from an array in redux?

You can check on the comment out code. That I try to use another approach but didn't work.

Thank you very much!

**Comment by Bilie** [comment]
Hi, here in the [docs](https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns/#inserting-and-removing-items-in-arrays) there is a good example how to remove items from an array

**Comment by rene-mdd** [comment]
@Bilie  Like this? I don't get it why doesn't work. Should I use the index instead of the id? With index I can use splice and slice.

https://github.com/dci-ber-fbw21/spa-store-blog-comments-rene-mdd/blob/a600d24add69d9e0c57ddb032db231a71f1122e6/src/store/app-reducer.js#L28
